# Generated by Django 4.2 on 2024-05-28 03:01

from django.db import migrations

def add_global_settings(apps, schema_editor):
    GlobalSettings = apps.get_model('massage', 'GlobalSettings')
    GlobalSettings.objects.get_or_create(name='Max Chairs', type='number', value='8')
    GlobalSettings.objects.get_or_create(name='PPN', type='percentage', value='10')

def remove_global_settings(apps, schema_editor):
    GlobalSettings = apps.get_model('massage', 'GlobalSettings')
    GlobalSettings.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_global_settings, remove_global_settings),
    ]