# Generated by Django 4.2 on 2024-05-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='static/massage/images/profile-placeholder.svg', upload_to='static/massage/images/employees/'),
        ),
    ]
