# Generated by Django 4.2 on 2024-05-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20240528_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
