# Generated by Django 4.2 on 2024-05-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_initial-data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepayment',
            old_name='total',
            new_name='total_fee',
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid Off'),
        ),
    ]
