# Generated by Django 4.2 on 2024-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_rename_total_employeepayment_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptservice',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Additional Service'),
        ),
    ]
