# Generated by Django 4.2 on 2024-05-21 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import massage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('massage', '0003_role_employee_user_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=massage.models.Employee.default_role, on_delete=django.db.models.deletion.CASCADE, to='massage.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=massage.models.Employee.default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
