# Generated by Django 4.2 on 2024-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0004_receiptservice_is_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='name',
            field=models.CharField(default='Max Chairs', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='type',
            field=models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage (0-100)'), ('text', 'Text'), ('time', 'Time')], default='number', max_length=10),
        ),
    ]
