# Generated by Django 4.2 on 2024-05-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import massage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('massage', '0005_rename_updated_at_employee_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='static/massage/images/woman-relaxing-spa 1.png', upload_to='static/massage/images/services/')),
                ('name', models.CharField(default='Service', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=massage.models.Service.default_admin, on_delete=django.db.models.deletion.CASCADE, related_name='service_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(default=massage.models.Service.default_admin, on_delete=django.db.models.deletion.CASCADE, related_name='service_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
