# Generated by Django 4.2 on 2024-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0006_alter_employee_address_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
