# Generated by Django 4.2 on 2024-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0008_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
